<?php
$COMPOSER_SHARED_AUTOLOAD_PATH = getenv('COMPOSER_SHARED_AUTOLOAD_PATH');

if ($COMPOSER_SHARED_AUTOLOAD_PATH === false)
{
    echo 'Unable getenv COMPOSER_SHARED_AUTOLOAD_PATH' . PHP_EOL;
    exit(1);
}

return require $COMPOSER_SHARED_AUTOLOAD_PATH;
